- name: 'Private key is ready here: {{ apache.key }}/{{ https.domain }}.key'
  command: openssl genrsa -out {{ apache.key }}/{{ https.domain }}.key 2048
  args:
    creates: '{{ apache.key }}/{{ https.domain }}.key'

- name: "Private key for Let's Encrypt Account"
  command: openssl genrsa -out {{ apache.key }}/account.key 2048
  args:
    creates: '{{ apache.key }}/account.key'

- name: "Remove CSR and CRT"
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '{{ apache.csr }}/{{ https.domain }}.csr'
    - '{{ apache.crt }}/{{ https.domain }}.crt'
#  when: '{{ remove_cert | default("False") | bool }}'
  tags: remove_cert

- name: 'Certifciate request is ready here: {{ apache.csr }}/{{ https.domain }}.csr'
  command: openssl req -new -sha256 -subj "{{ ssl_certs_fields }}" -key {{ apache.key }}/{{ https.domain }}.key -out {{ apache.csr }}/{{ https.domain }}.csr
  args:
    creates: '{{ apache.csr }}/{{ https.domain }}.csr'

#pak to slurpnut z https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt
- name: Creating CA
  template:
    src: "{{ https.intermed }}"
    dest: "{{ apache.interm }}/{{ https.intermed }}"
    mode: 0644
  when: https.intermed is defined

- name: "Requesting Let's encrypt challange for the domain."
  letsencrypt:
    account_key: '{{ apache.key }}/account.key'
    account_email: '{{ apache_service_admin_email }}'
    acme_directory: "{{ acme_directory | default('https://acme-staging.api.letsencrypt.org/directory') }}"
    csr: '{{ apache.csr }}/{{ https.domain }}.csr'
    dest: '{{ apache.crt }}/{{ https.domain }}.crt'
  register: http_challenge

- debug:
    var: http_challenge

- debug:
    var: acme_directory

- name: Creating challenge dir
  file:
    path:  /srv/www/htdocs/webarchiv.cz/.well-known/acme-challenge/
    state: directory

- name: Creating challenge file
  copy:
    dest: /srv/www/htdocs/webarchiv.cz/{{ http_challenge['challenge_data']['{{ https.domain }}']['http-01']['resource'] }}
    content: "{{ http_challenge['challenge_data']['{{ https.domain }}']['http-01']['resource_value'] }}"
  when: http_challenge | changed

- name: "Let's encrypt cert for domain: {{ https.domain }} is here: {{ apache.crt }}/{{ https.domain }}"
  letsencrypt:
    account_key: '{{ apache.key }}/account.key'
    acme_directory: '{{ acme_directory | default("https://acme-staging.api.letsencrypt.org/directory") }}'
    csr: '{{ apache.csr }}/{{ https.domain }}.csr'
    dest: '{{ apache.crt }}/{{ https.domain }}.crt'
    data: "{{ http_challenge }}"
