- name: Private key is ready
  command: openssl genrsa -out /etc/apache2/ssl.key/private-{{ https.domain }}.key 2048
  args:
    creates: /etc/apache2/ssl.key/private-{{ https.domain }}.key

- name: Creating CSR
  command: openssl req -new -sha256 -subj "{{ ssl_certs_fields }}" -key /etc/apache2/ssl.key/private-{{ https.domain }}.key -out /etc/apache2/ssl.csr/{{ https.domain }}.csr
  args:
    creates: /etc/apache2/ssl.csr/{{ https.domain }}.csr

- name: "Let's encrypt {{ https.domain }}"
  letsencrypt:
    account_key: /etc/apache2/ssl.key/private-{{ https.domain }}.key
    account_email: '{{ apache_service_admin_email }}'
    csr: /etc/apache2/ssl.csr/{{ https.domain }}.csr
    dest: /etc/apache2/ssl.crt/{{ https.domain }}.crt
  register: webarchiv_cz_challenge
