  #- name: Certbot repository is cloned
  #  git:
  #    dest: /opt/certbot
  #    clone: yes
  #    repo: https://github.com/certbot/certbot
  #    force: yes

    #- name: Conditional issuing of certificate
    #  shell: ./certbot-auto certonly --webroot --email {{ apache_service_admin_email }} --agree-tos --webroot-path={{ apache_webroot }} -d {{ apache_service_host }} > ansible-certification.log;
    #  args:
    #    chdir: /opt/certbot
    #    creates: ansible-certification.log
