- name: Apache HTTP configuration in place
  copy:
    src: "{{ http.conf }}"
    dest: "/etc/apache2/vhosts.d/{{ http.domain }}.http.conf"
    mode: 0644
  when:
    - http.domain is defined
    - http.conf is defined

- name: Apache HTTPS configuration at place
  copy:
    src: "{{ https.conf }}"
    dest: "/etc/apache2/vhosts.d/{{ https.domain }}.https.conf"
    mode: 0644
  when:
    - https.domain is defined
    - https.conf is defined
