---
# tasks file for NLCR.apache

- name: 'Distro non-specific provision'
  include: provision.yml

#ToDO python packages

#- name: Generate RSA (dhparams) file
#  file: path=/etc/ssl/certs owner=root group=root state=link state=directory mode=777

- name: 'Distro specific domain configuration'
  include: configuration-{{ ansible_os_family }}.yml

- name: 'Certbot provision'
  include: certbot.yml
  when: apache.https_domain is defined
