---
# tasks file for NLCR.apache

- name: 'Distro non-specific common tasks'
  include: common.yml

- name: 'SSL Certification'
  include: certbot-{{ ansible_os_family }}.yml
  when: https.domain is defined

- name: 'Distro specific domain configuration'
  include: configuration-{{ ansible_os_family }}.yml
