---
# tasks file for NLCR.apache

- name: 'Apache and openssl is installed'
  package:
    name: httpd,openssl

- name: Include OS specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: 'SSL Certification'
  include: certbot.yml
  when: https.domain is defined

- name: Apache Configuration
  include: configure-apache.yml
