---
# tasks file for NLCR.apache

- name: 'Apache and openssl is installed'
  package:
    name: httpd,openssl

- name: OS specific variables are ready
  include_vars: '{{ ansible_os_family }}.yml'

- name: 'Apache HTTP configuration is deployed.'
  template:
    src: "{{ http.conf }}"
    dest: "{{ apache.conf }}/{{ http.domain }}.http.conf"
    mode: 0644
  when:
    - http.domain is defined
    - http.conf is defined

- name: 'SSL Certification'
  include: certbot.yml
  when: https.domain is defined

- debug:
    var: "{{ http.conf }}"

- debug:
    var:  "{{ https.domain }}"

- name: 'Apache HTTPS configuration is deployed.'
  template:
    src: "{{ https.conf }}"
    dest: "{{ apache.conf }}/{{ https.domain }}.https.conf"
    mode: 0644
  when:
    - https.domain is defined
    - https.conf is defined
